params = {'backend': 'ps',
          'axes.labelsize': 22,
          'font.family': 'STIXGeneral',
          'mathtext.fontset': 'stix',
          'font.size': 22,
          'legend.fontsize': 22,
          'xtick.labelsize': 18,
          'ytick.labelsize': 18,
          'text.usetex': True,
          'axes.grid': False,
          'axes.spines.bottom': True,
          'axes.spines.left': True,
          'axes.spines.right': False,
          'axes.spines.top': False,
          'font.weight': 'bold'}